### ISSUE TITLE
URI 

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#10]
See crash mail 3/2 10:15

APP_VERSION_CODE=4
APP_VERSION_NAME=Muses App version v1.4
ANDROID_VERSION=4.1.2
PHONE_MODEL=LG-P760
STACK_TRACE=java.lang.RuntimeException: An error occured while executing
doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at
java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
at java.net.URI.parseURI(URI.java:353)
at java.net.URI.<init>(URI.java:204)
at java.net.URI.create(URI.java:725)
at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:79)
at
eu.musesproject.client.connectionmanager.HttpConnectionsHelper.doSecurePost(HttpConnectionsHelper.java:127)
at
eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:204)
at
eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:195)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 4 more
java.lang.NullPointerException
at java.net.URI.parseURI(URI.java:353)
at java.net.URI.<init>(URI.java:204)
at java.net.URI.create(URI.java:725)
at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:79)
at
eu.musesproject.client.connectionmanager.HttpConnectionsHelper.doSecurePost(HttpConnectionsHelper.java:127)
at
eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:204)
at
eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:195)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)

LOGCAT=
[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at java.lang.Runtime.exec(Runtime.java:184)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at com.stericson.RootShell.execution.Shell.<init>(Shell.java:144)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:848)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:834)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at com.stericson.RootShell.execution.Shell.startRootShell(Shell.java:826)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at com.stericson.RootShell.RootShell.isAccessGiven(RootShell.java:372)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:616)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at
eu.musesproject.client.contextmonitoring.sensors.DeviceProtectionSensor.checkRootPermissionGiven(DeviceProtectionSensor.java:187)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at
eu.musesproject.client.contextmonitoring.sensors.DeviceProtectionSensor.createContextEvent(DeviceProtectionSensor.java:119)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at
eu.musesproject.client.contextmonitoring.sensors.DeviceProtectionSensor.access$200(DeviceProtectionSensor.java:54)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at
eu.musesproject.client.contextmonitoring.sensors.DeviceProtectionSensor$CreateContextEventAsync.doInBackground(DeviceProtectionSensor.java:326)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at
eu.musesproject.client.contextmonitoring.sensors.DeviceProtectionSensor$CreateContextEventAsync.doInBackground(DeviceProtectionSensor.java:321)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at android.os.AsyncTask$2.call(AsyncTask.java:287)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at java.util.concurrent.FutureTask.run(FutureTask.java:137)

[ 02-03 09:25:41.037 15603:16495 W/System.err ]
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)

[ 02-03 09:25:41.045 15603:16495 W/System.err ]
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)

[ 02-03 09:25:41.045 15603:16495 W/System.err ]
at java.lang.Thread.run(Thread.java:856)

[ 02-03 09:25:41.045 15603:16495 W/System.err ]
Caused by: java.io.IOException: Permission denied

[ 02-03 09:25:41.045 15603:16495 W/System.err ]
at java.lang.ProcessManager.exec(Native Method)

[ 02-03 09:25:41.045 15603:16495 W/System.err ]
at java.lang.ProcessManager.exec(ProcessManager.java:209)

[ 02-03 09:25:41.045 15603:16495 W/System.err ]
... 20 more

[ 02-03 09:25:48.795 16877:16877 E/Trace    ]
error opening trace file: No such file or directory (2)

[ 02-03 09:25:48.974 16877:16877 W/ACRA     ]
eu.musesproject.client reports will be sent by email (if accepted by user).

[ 02-03 09:25:58.803 16910:16910 E/Trace    ]
error opening trace file: No such file or directory (2)

[ 02-03 09:25:58.928 16910:16910 W/ACRA     ]
eu.musesproject.client reports will be sent by email (if accepted by user).

[ 02-03 09:26:05.724 16923:16923 E/Trace    ]
error opening trace file: No such file or directory (2)

[ 02-03 09:26:05.842 16923:16923 W/ACRA     ]
eu.musesproject.client reports will be sent by email (if accepted by user).

[ 02-03 09:27:38.795 17167:17167 E/Trace    ]
error opening trace file: No such file or directory (2)

[ 02-03 09:27:38.912 17167:17167 W/ACRA     ]
eu.musesproject.client reports will be sent by email (if accepted by user).

[ 02-03 09:30:18.779 17167:17887 W/dalvikvm ]
threadid=10: thread exiting with uncaught exception (group=0x413102a0)

[ 02-03 09:30:18.779 17167:17887 E/ACRA     ]
ACRA caught a RuntimeException exception for eu.musesproject.client.
Building report.

[ 02-03 09:30:19.076 17167:17887 I/ACRA     ]
READ_LOGS granted! ACRA can include LogCat and DropBox data.

**Comment by mrburvall** [comment]
Not visible after restructuring of ConnectionManager.
