### ISSUE TITLE
ConnectionManager, DoPost IllegalArgumentException

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#11]
Description: 
Error when sending data to server.
Discovered by trial user, see crash report 3/2 13:41 

Version: 
APP_VERSION_CODE=4 
APP_VERSION_NAME=Muses App version v1.4 
ANDROID_VERSION=4.4.2 
PHONE_MODEL=Aquaris E5 HD 

Reproduce:  

Work Around: Unknown

Solution: N/A 

Logs: 
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground() 
at android.os.AsyncTask$3.done(AsyncTask.java:300) 
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355) 
at java.util.concurrent.FutureTask.setException(FutureTask.java:222) 
at java.util.concurrent.FutureTask.run(FutureTask.java:242) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841) 
Caused by: java.lang.IllegalArgumentException 
at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:82) 
at eu.musesproject.client.connectionmanager.HttpConnectionsHelper.doSecurePost(HttpConnectionsHelper.java:127) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:204) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:195) 
at android.os.AsyncTask$2.call(AsyncTask.java:288) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
... 3 more 
java.lang.IllegalArgumentException 
at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:82) 
at eu.musesproject.client.connectionmanager.HttpConnectionsHelper.doSecurePost(HttpConnectionsHelper.java:127) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:204) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:195) 
at android.os.AsyncTask$2.call(AsyncTask.java:288) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841) 

LOGCAT=--------- beginning of /dev/log/main 
[ 02-03 13:26:47.478 24978:0x6268 E/ACRA ] 
ACRA caught a RuntimeException exception for eu.musesproject.client. Building report. 

[ 02-03 13:26:50.609 24978:0x6274 E/ACRA ] 
eu.musesproject.client fatal error : An error occured while executing doInBackground() 
java.lang.RuntimeException: An error occured while executing doInBackground() 
at android.os.AsyncTask$3.done(AsyncTask.java:300) 
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355) 
at java.util.concurrent.FutureTask.setException(FutureTask.java:222) 
at java.util.concurrent.FutureTask.run(FutureTask.java:242) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841) 
Caused by: java.lang.IllegalArgumentException 
at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:82) 
at eu.musesproject.client.connectionmanager.HttpConnectionsHelper.doSecurePost(HttpConnectionsHelper.java:127) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:204) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:195) 
at android.os.AsyncTask$2.call(AsyncTask.java:288) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
... 3 more 

[ 02-03 13:28:01.633 25211:0x6327 E/ACRA ] 
ACRA caught a RuntimeException exception for eu.musesproject.client. Building report. 

[ 02-03 13:28:04.703 25211:0x6330 E/ACRA ] 
eu.musesproject.client fatal error : An error occured while executing doInBackground() 
java.lang.RuntimeException: An error occured while executing doInBackground() 
at android.os.AsyncTask$3.done(AsyncTask.java:300) 
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355) 
at java.util.concurrent.FutureTask.setException(FutureTask.java:222) 
at java.util.concurrent.FutureTask.run(FutureTask.java:242) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841) 
Caused by: java.lang.IllegalArgumentException 
at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:82) 
at eu.musesproject.client.connectionmanager.HttpConnectionsHelper.doSecurePost(HttpConnectionsHelper.java:127) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:204) 
at eu.musesproject.client.connectionmanager.ConnectionManager$HttpClientAsyncThread.doInBackground(ConnectionManager.java:195) 
at android.os.AsyncTask$2.call(AsyncTask.java:288) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
... 3 more 

[ 02-03 13:28:51.623 25432:0x645a E/ACRA ] 
ACRA caught a RuntimeException exception for eu.musesproject.client. Building report. 

Enviado desde IBM Notes Traveler

**Comment by mrburvall** [comment]
Not visible after restructuring of ConnectionManager.
