### ISSUE TITLE
Nullpointer when accessing to all resources in database while making decision

### ISSUE THREAD

**Issue by szamarripa** [MusesProject/MusesClient#14]
APP_VERSION_CODE=5
APP_VERSION_NAME=Muses App version v1.5
ANDROID_VERSION=4.4.4
PHONE_MODEL=D6503
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.getAllResources(DBManager.java:1850)
at eu.musesproject.client.decisionmaker.DecisionMaker.makeDecision(DecisionMaker.java:120)
at eu.musesproject.client.usercontexteventhandler.UserContextEventHandler.retrieveDecision(UserContextEventHandler.java:259)
at eu.musesproject.client.usercontexteventhandler.UserContextEventHandler.send(UserContextEventHandler.java:182)
at eu.musesproject.client.contextmonitoring.UserContextMonitoringController.sendUserAction(UserContextMonitoringController.java:93)
at eu.musesproject.client.contextmonitoring.SensorController$ContextEventBus.onEvent(SensorController.java:278)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor.createContextEvent(AppSensor.java:126)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor.access$3(AppSensor.java:100)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor$AppObserver.doInBackground(AppSensor.java:183)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor$AppObserver.doInBackground(AppSensor.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.getAllResources(DBManager.java:1850)
at eu.musesproject.client.decisionmaker.DecisionMaker.makeDecision(DecisionMaker.java:120)
at eu.musesproject.client.usercontexteventhandler.UserContextEventHandler.retrieveDecision(UserContextEventHandler.java:259)
at eu.musesproject.client.usercontexteventhandler.UserContextEventHandler.send(UserContextEventHandler.java:182)
at eu.musesproject.client.contextmonitoring.UserContextMonitoringController.sendUserAction(UserContextMonitoringController.java:93)
at eu.musesproject.client.contextmonitoring.SensorController$ContextEventBus.onEvent(SensorController.java:278)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor.createContextEvent(AppSensor.java:126)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor.access$3(AppSensor.java:100)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor$AppObserver.doInBackground(AppSensor.java:183)
at eu.musesproject.client.contextmonitoring.sensors.AppSensor$AppObserver.doInBackground(AppSensor.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

LOGCAT=--------- beginning of /dev/log/main
[ 02-08 10:16:54.942 28695:28722 W/DecisionMaker ]
Policy Device Decision: deny

[ 02-08 10:16:54.942 28695:28722 W/DecisionMaker ]
Result decision: STRONG_DENY

[ 02-08 10:16:54.942 28695:28722 W/DecisionMaker ]
Risk treatment: You are trying to disable accessibility, which is an important security mechanism for MUSES.
This can cause the device having a lower level of security.

[ 02-08 10:16:54.952 28695:28711 W/dalvikvm ]
threadid=11: thread exiting with uncaught exception (group=0x415f2d88)

[ 02-08 10:16:54.952 28695:28711 E/ACRA     ]
ACRA caught a RuntimeException exception for eu.musesproject.client. Building report.

[ 02-08 10:16:54.962 28695:16320 W/ResourceType ]
CREATING STRING CACHE OF 44 bytes

[ 02-08 10:16:54.982 28695:28711 I/ACRA     ]
READ_LOGS granted! ACRA can include LogCat and DropBox data.

**Comment by szamarripa** [comment]
This would solve the following issues:

-Caused by: java.lang.NullPointerException 
at eu.musesproject.client.db.handler.DBManager.getAllResources(DBManager.java:1850) 
-java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.getDevId(DBManager.java:463)
-Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.addAction(DBManager.java:920)
-Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.getStoredContextEventByActionId(DBManager.java:1357)
-Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.addProperty(DBManager.java:1389)
-Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.getAllSensorConfigItemsBySensorType(DBManager.java:1712)
-Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.insertConnectionProperties(DBManager.java:487)
-Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.addActionProperty(DBManager.java:917)
-Caused by: java.lang.NullPointerException
at eu.musesproject.client.db.handler.DBManager.getPropertiesOfContextEvent(DBManager.java:1290)
